79 articles commenting
Blogplace/Blogplace.Backend pull request #87
Opened 2024-10-08 13:11 UTC by Navio1430

2024-10-08 22:50 UTC, Marcin99b requested changes

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Tests.Integration/Data/CommentsRepositoryFake.cs
> +    public List<Comment> Comments { get; private set; }
dodaj tam = [] bo teraz jest null

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Tests.Integration/Data/CommentsRepositoryFake.cs
> +    public static Comment? StandardUserCommentOnStandardUserArticle { get; set; }
Potężna nazwa
Nie da sie tego jakoś prościej nazwać?

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Tests.Integration/Tests/CommentsTests.cs
> +        // TODO: check if the comment actually exist in the repository
łatwo można wyciągnąć repo z `_factory`, ale można zrobić to requestem i od razu upewniać sie czy zwraca dodane komentarze

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Web/Commons/Logging/EventLogger.cs
> +        => this.Info(nameof(this.UserCreatedComment), new { UserId = userId, CommentId = commentId });
literówka, ma być UserUpdatedComment

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Web/Domain/Comments/Requests/DeleteCommentRequestHandler.cs
> +        var comment = await repository.Get(commentId);
w sumie zamiast `var commentId = request.CommentId;` możesz tutaj użyć `request.CommentId`

2024-10-08 22:50 UTC, Marcin99b commented on Blogplace.Web/ServiceExtensions.cs
> +        builder.Services.AddSingleton<ILogger>(logger);
zostawiłbym tak jak było, żeby było jawnie wiadomo że chodzi o seriloga

2024-10-09 13:44 UTC, Marcin99b commented on Blogplace.Tests.Integration/Tests/CommentsTests.cs
> +        // TODO: Check if the comment doesn't exist in the repository
Tak jak komentarz wyżej, zamiast sprawdzania repo, można sprawdzać odpowiedź z api

Usuwanie niekoniecznie musi być fizycznym usunięciem z bazy, lepiej sprawdzać czy po usunięciu nie pojawia sie na liście

Można to zaprojektować na różne sposoby, testy powinny być odporne na zmiany szczegółów w kodzie

2024-10-10 13:54 UTC, Navio1430 commented on Blogplace.Web/Domain/Comments/Requests/DeleteCommentRequestHandler.cs
> +        var comment = await repository.Get(commentId);
Dodałem zmienną dlatego, że jest w 3 miejsach używana w handlerze. Niby można zamienić wszędzie na request.CommentId ale wydaje mi się, że tak jest bardziej czytelnie.

2024-10-10 22:31 UTC, Marcin99b commented on Blogplace.Web/Domain/Comments/Comment.cs
> +﻿namespace Blogplace.Web.Domain.Comments;
bardziej Articles bo domenowo komentarz to część artykułu a nie coś osobnego i niezależnego

2024-10-11 14:47 UTC, Navio1430 commented
Before merge: Change ChildCount property each time comment is being created/deleted

2024-10-15 01:55 UTC, Marcin99b commented on Blogplace.Web/Commons/Logging/EventLogger.cs
> +        => this.Info(nameof(this.UserCreatedComment), new { UserId = userId, CommentId = commentId });
tutaj codecov widzi brak pokrycia, lepiej byłoby mieć je w takich podstawowych scenariuszach

2024-10-15 01:56 UTC, Marcin99b commented on Blogplace.Web/Controllers/V1/CommentsController.cs
> +    public Task<CreateCommentResponse> Create(CreateCommentRequest request) => mediator.Send(request);
codecov nie widzi pokrycia testami

2024-10-16 01:13 UTC, Marcin99b approved these changes

2024-10-16 22:00 UTC, merged